### ISSUE TITLE
device that can be used?

### ISSUE THREAD

**Issue by antimodular** [naychrist/ofxDdp#1]
hi.
your addon looks interesting.
can you post a few examples of devices that can be used with your addon?
thanks a bunch.

**Comment by naychrist** [comment]
Hi there, I use this library with the Minleon NDB (Network Distribution Box)

http://www.teklights.com/products/network-data-box-ndb
http://www.3waylabs.com/triklits/ndb.html

These boxes work with DDP or Artnet. So far there are a number of LED products such as the Minleon triklits and tubes, which can be connected to these control boxes. You can find some of them at the same teklights online store above.
